export const tmdbWatchRegionCodes = [
  { name: "All Regions", value: null },
  { name: "United Arab Emirates", value: "AE" },
  { name: "Argentina", value: "AR" },
  { name: "Austria", value: "AT" },
  { name: "Australia", value: "AU" },
  { name: "Belgium", value: "BE" },
  { name: "Bulgaria", value: "BG" },
  { name: "Bolivia", value: "BO" },
  { name: "Brazil", value: "BR" },
  { name: "Canada", value: "CA" },
  { name: "Switzerland", value: "CH" },
  { name: "Chile", value: "CL" },
  { name: "Colombia", value: "CO" },
  { name: "Costa Rica", value: "CR" },
  { name: "Czech Republic", value: "CZ" },
  { name: "Germany", value: "DE" },
  { name: "Denmark", value: "DK" },
  { name: "Ecuador", value: "EC" },
  { name: "Estonia", value: "EE" },
  { name: "Egypt", value: "EG" },
  { name: "Spain", value: "ES" },
  { name: "Finland", value: "FI" },
  { name: "France", value: "FR" },
  { name: "United Kingdom", value: "GB" },
  { name: "Greece", value: "GR" },
  { name: "Guatemala", value: "GT" },
  { name: "Hong Kong", value: "HK" },
  { name: "Honduras", value: "HN" },
  { name: "Hungary", value: "HU" },
  { name: "Indonesia", value: "ID" },
  { name: "Ireland", value: "IE" },
  { name: "Israel", value: "IL" },
  { name: "India", value: "IN" },
  { name: "Italy", value: "IT" },
  { name: "Japan", value: "JP" },
  { name: "Lithuania", value: "LT" },
  { name: "Latvia", value: "LV" },
  { name: "Mexico", value: "MX" },
  { name: "Malaysia", value: "MY" },
  { name: "Netherlands", value: "NL" },
  { name: "Norway", value: "NO" },
  { name: "New Zealand", value: "NZ" },
  { name: "Peru", value: "PE" },
  { name: "Philippines", value: "PH" },
  { name: "Poland", value: "PL" },
  { name: "Portugal", value: "PT" },
  { name: "Paraguay", value: "PY" },
  { name: "Russia", value: "RU" },
  { name: "Saudi Arabia", value: "SA" },
  { name: "Sweden", value: "SE" },
  { name: "Singapore", value: "SG" },
  { name: "Slovenia", value: "SI" },
  { name: "Slovakia", value: "SK" },
  { name: "Thailand", value: "TH" },
  { name: "Turkey", value: "TR" },
  { name: "Taiwan", value: "TW" },
  { name: "United States", value: "US" },
  { name: "Venezuela", value: "VE" },
  { name: "South Africa", value: "ZA" },
  { name: "Cape Verde", value: "CV" },
  { name: "Ghana", value: "GH" },
  { name: "Mauritius", value: "MU" },
  { name: "Mozambique", value: "MZ" },
  { name: "Uganda", value: "UG" },
];
