//complex type-specific language codes
export const languageCodes = {
  // Most Common Languages
  en: { name: "English", nativeName: "English" },
  es: { name: "Spanish", nativeName: "Español" },
  fr: { name: "French", nativeName: "Français" },
  de: { name: "German", nativeName: "Deutsch" },
  it: { name: "Italian", nativeName: "Italiano" },
  pt: { name: "Portuguese", nativeName: "Português" },
  ru: { name: "Russian", nativeName: "Русский" },
  ja: { name: "Japanese", nativeName: "日本語" },
  ko: { name: "Korean", nativeName: "한국어" },
  zh: { name: "Chinese", nativeName: "中文" },
  ar: { name: "Arabic", nativeName: "العربية" },
  hi: { name: "Hindi", nativeName: "हिन्दी" },
  tr: { name: "Turkish", nativeName: "Türkçe" },
  nl: { name: "Dutch", nativeName: "Nederlands" },
  pl: { name: "Polish", nativeName: "Polski" },
  sv: { name: "Swedish", nativeName: "Svenska" },
  no: { name: "Norwegian", nativeName: "Norsk" },
  da: { name: "Danish", nativeName: "Dansk" },
  fi: { name: "Finnish", nativeName: "Suomi" },
  cs: { name: "Czech", nativeName: "Čeština" },
  hu: { name: "Hungarian", nativeName: "Magyar" },
  ro: { name: "Romanian", nativeName: "Română" },
  el: { name: "Greek", nativeName: "Ελληνικά" },
  he: { name: "Hebrew", nativeName: "עברית" },
  th: { name: "Thai", nativeName: "ไทย" },
  vi: { name: "Vietnamese", nativeName: "Tiếng Việt" },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia" },
  ms: { name: "Malay", nativeName: "Bahasa Melayu" },
  fa: { name: "Persian", nativeName: "فارسی" },
  uk: { name: "Ukrainian", nativeName: "Українська" },

  // Additional European Languages
  bg: { name: "Bulgarian", nativeName: "Български" },
  hr: { name: "Croatian", nativeName: "Hrvatski" },
  sk: { name: "Slovak", nativeName: "Slovenčina" },
  sl: { name: "Slovenian", nativeName: "Slovenščina" },
  sr: { name: "Serbian", nativeName: "Српски" },
  et: { name: "Estonian", nativeName: "Eesti" },
  lv: { name: "Latvian", nativeName: "Latviešu" },
  lt: { name: "Lithuanian", nativeName: "Lietuvių" },
  is: { name: "Icelandic", nativeName: "Íslenska" },
  ga: { name: "Irish", nativeName: "Gaeilge" },
  mt: { name: "Maltese", nativeName: "Malti" },
  cy: { name: "Welsh", nativeName: "Cymraeg" },

  // Middle Eastern & Central Asian
  ku: { name: "Kurdish", nativeName: "کوردی" },
  az: { name: "Azerbaijani", nativeName: "Azərbaycan" },
  ka: { name: "Georgian", nativeName: "ქართული" },
  hy: { name: "Armenian", nativeName: "Հայերեն" },

  // South & Southeast Asian
  bn: { name: "Bengali", nativeName: "বাংলা" },
  ur: { name: "Urdu", nativeName: "اردو" },
  ta: { name: "Tamil", nativeName: "தமிழ்" },
  te: { name: "Telugu", nativeName: "తెలుగు" },
  ml: { name: "Malayalam", nativeName: "മലയാളം" },
  kn: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
  mr: { name: "Marathi", nativeName: "मराठी" },
  pa: { name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  si: { name: "Sinhala", nativeName: "සිංහල" },
  my: { name: "Burmese", nativeName: "မြန်မာ" },
  km: { name: "Khmer", nativeName: "ខ្មែរ" },
  lo: { name: "Lao", nativeName: "ລາວ" },

  // East Asian
  "zh-CN": { name: "Chinese (Simplified)", nativeName: "简体中文" },
  "zh-TW": { name: "Chinese (Traditional)", nativeName: "繁體中文" },
  "zh-HK": { name: "Chinese (Hong Kong)", nativeName: "香港中文" },

  // Latin American & Others
  "pt-BR": { name: "Portuguese (Brazil)", nativeName: "Português (Brasil)" },
  "pt-PT": {
    name: "Portuguese (Portugal)",
    nativeName: "Português (Portugal)",
  },
  "es-MX": { name: "Spanish (Mexico)", nativeName: "Español (México)" },
  "es-ES": { name: "Spanish (Spain)", nativeName: "Español (España)" },
  "en-US": { name: "English (US)", nativeName: "English (US)" },
  "en-GB": { name: "English (UK)", nativeName: "English (UK)" },
  "fr-CA": { name: "French (Canada)", nativeName: "Français (Canada)" },

  // African Languages
  af: { name: "Afrikaans", nativeName: "Afrikaans" },
  sw: { name: "Swahili", nativeName: "Kiswahili" },
  zu: { name: "Zulu", nativeName: "isiZulu" },
  xh: { name: "Xhosa", nativeName: "isiXhosa" },

  // Other Languages
  ca: { name: "Catalan", nativeName: "Català" },
  eu: { name: "Basque", nativeName: "Euskara" },
  gl: { name: "Galician", nativeName: "Galego" },
  sq: { name: "Albanian", nativeName: "Shqip" },
  mk: { name: "Macedonian", nativeName: "Македонски" },
  be: { name: "Belarusian", nativeName: "Беларуская" },
  kk: { name: "Kazakh", nativeName: "Қазақ" },
  uz: { name: "Uzbek", nativeName: "Oʻzbek" },
  mn: { name: "Mongolian", nativeName: "Монгол" },
  ne: { name: "Nepali", nativeName: "नेपाली" },

  // Special codes
  xx: { name: "No Language", nativeName: "No Language" },
  cn: { name: "Cantonese", nativeName: "粵語" },
};

export const countriesIso_3166_1Codes: Record<string, string> = {
  // North America
  US: "United States of America",
  CA: "Canada",
  MX: "Mexico",

  // Europe
  GB: "United Kingdom",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  RU: "Russia",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  NL: "Netherlands",
  BE: "Belgium",
  CH: "Switzerland",
  AT: "Austria",
  PL: "Poland",
  CZ: "Czech Republic",
  HU: "Hungary",
  GR: "Greece",

  // Asia
  CN: "China",
  JP: "Japan",
  KR: "South Korea",
  IN: "India",
  TH: "Thailand",
  ID: "Indonesia",
  VN: "Vietnam",
  PH: "Philippines",
  MY: "Malaysia",
  SG: "Singapore",
  HK: "Hong Kong",
  TW: "Taiwan",

  // Oceania
  AU: "Australia",
  NZ: "New Zealand",

  // South America
  BR: "Brazil",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",

  // Africa
  ZA: "South Africa",
  NG: "Nigeria",
  EG: "Egypt",
  KE: "Kenya",
};

export const countriesISO_639_1Codes: Record<string, string> = {
  aa: "Afar",
  ab: "Abkhazian",
  af: "Afrikaans",
  ak: "Akan",
  am: "Amharic",
  ar: "Arabic",
  an: "Aragonese",
  as: "Assamese",
  av: "Avaric",
  ay: "Aymara",
  az: "Azerbaijani",
  ba: "Bashkir",
  be: "Belarusian",
  bg: "Bulgarian",
  bh: "Bihari",
  bi: "Bislama",
  bm: "Bambara",
  bn: "Bengali",
  bo: "Tibetan",
  br: "Breton",
  bs: "Bosnian",
  ca: "Catalan",
  ce: "Chechen",
  ch: "Chamorro",
  co: "Corsican",
  cr: "Cree",
  cs: "Czech",
  cu: "Church Slavic",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  de: "German",
  dv: "Divehi",
  dz: "Dzongkha",
  ee: "Ewe",
  el: "Greek",
  en: "English",
  eo: "Esperanto",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  fa: "Persian",
  ff: "Fulah",
  fi: "Finnish",
  fj: "Fijian",
  fo: "Faroese",
  fr: "French",
  fy: "Western Frisian",
  ga: "Irish",
  gd: "Scottish Gaelic",
  gl: "Galician",
  gn: "Guarani",
  gu: "Gujarati",
  gv: "Manx",
  ha: "Hausa",
  he: "Hebrew",
  hi: "Hindi",
  ho: "Hiri Motu",
  hr: "Croatian",
  ht: "Haitian",
  hu: "Hungarian",
  hy: "Armenian",
  hz: "Herero",
  ia: "Interlingua",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  ii: "Sichuan Yi",
  ik: "Inupiaq",
  io: "Ido",
  is: "Icelandic",
  it: "Italian",
  iu: "Inuktitut",
  ja: "Japanese",
  jv: "Javanese",
  ka: "Georgian",
  kg: "Kongo",
  ki: "Kikuyu",
  kj: "Kuanyama",
  kk: "Kazakh",
  kl: "Kalaallisut",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  kr: "Kanuri",
  ks: "Kashmiri",
  ku: "Kurdish",
  kv: "Komi",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lb: "Luxembourgish",
  lg: "Ganda",
  li: "Limburgan",
  ln: "Lingala",
  lo: "Lao",
  lt: "Lithuanian",
  lu: "Luba-Katanga",
  lv: "Latvian",
  mg: "Malagasy",
  mh: "Marshallese",
  mi: "Maori",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mr: "Marathi",
  ms: "Malay",
  mt: "Maltese",
  my: "Burmese",
  na: "Nauru",
  nb: "Norwegian Bokmål",
  nd: "North Ndebele",
  ne: "Nepali",
  ng: "Ndonga",
  nl: "Dutch",
  nn: "Norwegian Nynorsk",
  no: "Norwegian",
  nr: "South Ndebele",
  nv: "Navajo",
  ny: "Nyanja",
  oc: "Occitan",
  oj: "Ojibwa",
  om: "Oromo",
  or: "Oriya",
  os: "Ossetian",
  pa: "Punjabi",
  pi: "Pali",
  pl: "Polish",
  ps: "Pashto",
  pt: "Portuguese",
  qu: "Quechua",
  rm: "Romansh",
  rn: "Rundi",
  ro: "Romanian",
  ru: "Russian",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sc: "Sardinian",
  sd: "Sindhi",
  se: "Northern Sami",
  sg: "Sango",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  sm: "Samoan",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  ss: "Swati",
  st: "Southern Sotho",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tk: "Turkmen",
  tl: "Tagalog",
  tn: "Tswana",
  to: "Tongan",
  tr: "Turkish",
  ts: "Tsonga",
  tt: "Tatar",
  tw: "Twi",
  ty: "Tahitian",
  ug: "Uighur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vi: "Vietnamese",
  vo: "Volapük",
  wa: "Walloon",
  wo: "Wolof",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  za: "Zhuang",
  zh: "Chinese",
  zu: "Zulu",
  // TMDB-specific additions
  cn: "Cantonese",
  gb: "British English",
  sh: "Serbo-Croatian",
  zx: "No Language",
  xx: "No Language",
};
