export const tmdbCountryCodes = [
  { name: "All", value: null },
  { name: "Afrikaans", value: "af" },
  { name: "Arabic", value: "ar" },
  { name: "Belarusian", value: "be" },
  { name: "Bulgarian", value: "bg" },
  { name: "Bengali", value: "bn" },
  { name: "Bosnian", value: "bs" },
  { name: "Catalan", value: "ca" },
  { name: "Czech", value: "cs" },
  { name: "Welsh", value: "cy" },
  { name: "Danish", value: "da" },
  { name: "German", value: "de" },
  { name: "Greek", value: "el" },
  { name: "English", value: "en" },
  { name: "Esperanto", value: "eo" },
  { name: "Spanish", value: "es" },
  { name: "Estonian", value: "et" },
  { name: "Basque", value: "eu" },
  { name: "Persian", value: "fa" },
  { name: "Finnish", value: "fi" },
  { name: "French", value: "fr" },
  { name: "Irish", value: "ga" },
  { name: "Galician", value: "gl" },
  { name: "Hebrew", value: "he" },
  { name: "Hindi", value: "hi" },
  { name: "Croatian", value: "hr" },
  { name: "Haitian Creole", value: "ht" },
  { name: "Hungarian", value: "hu" },
  { name: "Indonesian", value: "id" },
  { name: "Icelandic", value: "is" },
  { name: "Italian", value: "it" },
  { name: "Japanese", value: "ja" },
  { name: "Georgian", value: "ka" },
  { name: "Kannada", value: "kn" },
  { name: "Korean", value: "ko" },
  { name: "Latin", value: "la" },
  { name: "Lithuanian", value: "lt" },
  { name: "Latvian", value: "lv" },
  { name: "Macedonian", value: "mk" },
  { name: "Malayalam", value: "ml" },
  { name: "Marathi", value: "mr" },
  { name: "Malay", value: "ms" },
  { name: "Maltese", value: "mt" },
  { name: "Dutch", value: "nl" },
  { name: "Norwegian", value: "no" },
  { name: "Occitan", value: "oc" },
  { name: "Polish", value: "pl" },
  { name: "Portuguese", value: "pt" },
  { name: "Portuguese (Brazil)", value: "pt-BR" },
  { name: "Romanian", value: "ro" },
  { name: "Russian", value: "ru" },
  { name: "Slovak", value: "sk" },
  { name: "Slovenian", value: "sl" },
  { name: "Serbian", value: "sr" },
  { name: "Swedish", value: "sv" },
  { name: "Tamil", value: "ta" },
  { name: "Telugu", value: "te" },
  { name: "Thai", value: "th" },
  { name: "Tagalog", value: "tl" },
  { name: "Turkish", value: "tr" },
  { name: "Ukrainian", value: "uk" },
  { name: "Urdu", value: "ur" },
  { name: "Vietnamese", value: "vi" },
  { name: "Chinese (Simplified)", value: "zh" },
  { name: "Chinese (Traditional)", value: "zh-TW" },
];

export const tmdbRating = [
  { value: null, name: "Any rating" },
  { value: "1", name: "1+ " },
  { value: "2", name: "2+ " },
  { value: "3", name: "3+ " },
  { value: "4", name: "4+ " },
  { value: "5", name: "5+ " },
  { value: "6", name: "6+ " },
  { value: "7", name: "7+ " },
  { value: "8", name: "8+ " },
  { value: "9", name: "9+ " },
];

export const countryNameCodes: Record<string, string> = {
  US: "United States of America",
  GB: "United Kingdom",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  JP: "Japan",
  KR: "South Korea",
  CN: "China",
  CA: "Canada",
  AU: "Australia",
  RU: "Russia",
  TR: "Turkey",
  IR: "Iran",
  IQ: "Iraq",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  EG: "Egypt",
  BR: "Brazil",
  AR: "Argentina",
  MX: "Mexico",
  IN: "India",
};

export const TMDBSeriesTypes = {
  Documentary: " with_type=0 ", // Documentary
  News: "with_type=1", // News
  Miniseries: "with_type=2", // Miniseries ✅
  Reality: "with_type=3", // Reality
  Scripted: "with_type=4", // Scripted
  "Talk Show": "with_type=5", // Talk Show
  Video: "with_type=6", // Video
};
